version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: fixmyrv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fixmyrv
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with existing postgres on 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: sj26/mailcatcher
    container_name: fixmyrv-mailcatcher
    ports:
      - "1026:1025"  # SMTP
      - "1081:1080"  # Web interface
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1080"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  default:
    name: fixmyrv-network
