[build]
buildCommand = "cd backend && npm ci && npm run build"

[start]
startCommand = "cd backend && npm start"

[build.env]
NODE_ENV = "production"
FORCE_DB_SYNC = "true"

[variables]
NODE_ENV = "production"
FORCE_DB_SYNC = "true"
